---
title: Classwork 2
subtitle: "Omitted Variable Bias; Bad Controls"
date: 2026-01-26
code-fold: show
execute: 
  echo: true
  warning: false
  message: false
toc: true
from: markdown+emoji
---
```{r}
#| include: false

library(knitr)
library(rmarkdown)
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(broom)
library(stargazer)
library(tibble)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```


# Omitted Variable Bias
```{r}
#| results: asis

library(tidyverse)
library(broom)
library(stargazer)

oj <- read_csv('https://bcdanl.github.io/data/dominick_oj_ad.csv')

reg_short <- lm(log(sales) ~ log(price),
                data = oj)

reg_long <- lm(log(sales) ~ log(price) + brand,
                data = oj)

stargazer(reg_short, reg_long,
          type = 'html')
```


```{r}
#| results: asis
reg_1st <- lm(log(price) ~ brand,
              data = oj)

aug_m2 <- augment(reg_1st)    # broom::augment()

reg_2nd <- lm(log(sales) ~ aug_m2$.resid,
              data = oj)

stargazer(reg_long, reg_2nd,
          type = 'html')
```



# Bad Controls

## Education, Occupation, and Wages

```{r}
#| results: asis
set.seed(1)

tb <- tibble( 
  highschool_degree = ifelse(runif(10000)>=0.5, 1,0), # highschool_degree indicator variable
  ability = rnorm(10000), # e.g., talent, usually unobserved.
  occupation_index = 1 + 2*ability - 2*highschool_degree + rnorm(10000), # true data generating process for occupation_index variable
  wage = 1 - 1*highschool_degree + 1*occupation_index + 2*ability + rnorm(10000) # true data generating process for wage variable
)

lm_1 <- lm(wage ~ highschool_degree, tb)
lm_2 <- lm(wage ~ highschool_degree + occupation_index, tb)
lm_3 <- lm(wage ~ highschool_degree + occupation_index + ability, tb)

stargazer::stargazer(lm_1,lm_2,lm_3, 
                     column.labels = c("Biased Unconditional", 
                                       "Biased",
                                       "Unbiased Conditional"),
                     type = 'html')
```

## Fertilizer, Plant Height, and Crop Yield

```{r}
#| results: asis
set.seed(2026)

# Simulate 10,000 plots
tb3 <- tibble(
  fertilizer    = rbinom(10000, 1, 0.5),       # 0 = no fertilizer, 1 = fertilizer applied
  soil_quality  = rnorm(10000),                # unobserved “plot fertility”
  # Height (cm) is boosted by fertilizer *and* by soil quality
  height        = 50 + 8 * fertilizer + 5 * soil_quality + rnorm(10000),
  # Yield (bushels) depends on fertilizer, height, and soil quality
  yield         = 200 
  + 10 * fertilizer      # direct effect of fertilizer
  + 3  * height          # return to plant height
  + 6  * soil_quality    # underlying soil fertility
  + rnorm(10000)
)

# 1) Omitting height: picks up both direct and indirect effects
lm1 <- lm(yield ~ fertilizer,         data = tb3)
# 2) Controlling for height: "blocks" the mediation channel
lm2 <- lm(yield ~ fertilizer + height, data = tb3)
# 3) Also control soil_quality to recover the true direct effect
lm3 <- lm(yield ~ fertilizer + height + soil_quality, data = tb3)

stargazer(
  lm1, lm2, lm3,
  column.labels   = c("Omit Height (Biased)", 
                      "Control Height (More Biased)",
                      "Also Soil (Unbiased)"),
  dep.var.labels  = "yield",
  keep            = c("fertilizer", "height", "soil_quality"),
  covariate.labels= c("Fertilizer", "Plant Height", "Soil Quality"),
  type            = "html"
)
```

